// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/GiftBuffInfo.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.data;

public interface GiftBuffInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:GiftBuffInfo)
        com.google.protobuf.MessageOrBuilder {
}
