// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/GradeBuffInfo.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.data;

/**
 * <p>GradeBuffInfoOrBuilder interface.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public interface GradeBuffInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:GradeBuffInfo)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 buffLevel = 1;</code>
     *
     * @return The buffLevel.
     */
    long getBuffLevel();

    /**
     * <code>int32 status = 2;</code>
     *
     * @return The status.
     */
    int getStatus();

    /**
     * <code>int64 endTime = 3;</code>
     *
     * @return The endTime.
     */
    long getEndTime();

    /**
     * <code>map&lt;int64, int64&gt; statsInfoMap = 4;</code>
     *
     * @return a int
     */
    int getStatsInfoMapCount();

    /**
     * <code>map&lt;int64, int64&gt; statsInfoMap = 4;</code>
     *
     * @param key a long
     * @return a boolean
     */
    boolean containsStatsInfoMap(
            long key);

    /**
     * Use {@link #getStatsInfoMapMap()} instead.
     *
     * @return a {@link java.util.Map} object
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, java.lang.Long>
    getStatsInfoMap();

    /**
     * <code>map&lt;int64, int64&gt; statsInfoMap = 4;</code>
     *
     * @return a {@link java.util.Map} object
     */
    java.util.Map<java.lang.Long, java.lang.Long>
    getStatsInfoMapMap();

    /**
     * <code>map&lt;int64, int64&gt; statsInfoMap = 4;</code>
     *
     * @param key          a long
     * @param defaultValue a long
     * @return a long
     */
    long getStatsInfoMapOrDefault(
            long key,
            long defaultValue);

    /**
     * <code>map&lt;int64, int64&gt; statsInfoMap = 4;</code>
     *
     * @param key a long
     * @return a long
     */
    long getStatsInfoMapOrThrow(
            long key);

    /**
     * <code>.Image buffBadge = 5;</code>
     *
     * @return Whether the buffBadge field is set.
     */
    boolean hasBuffBadge();

    /**
     * <code>.Image buffBadge = 5;</code>
     *
     * @return The buffBadge.
     */
    cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.Image getBuffBadge();

    /**
     * <code>.Image buffBadge = 5;</code>
     *
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.ImageOrBuilder} object
     */
    cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.ImageOrBuilder getBuffBadgeOrBuilder();
}
