// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/IndustryCertification.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.data;

public final class IndustryCertificationOuterClass {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_IndustryCertification_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_IndustryCertification_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n(webcast/data/IndustryCertification.pro" +
                        "to\"\027\n\025IndustryCertificationB?\n;cool.scx." +
                        "live_room_watcher.douyin.proto_entity.we" +
                        "bcast.dataP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_IndustryCertification_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_IndustryCertification_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_IndustryCertification_descriptor,
                new java.lang.String[]{});
    }
    private IndustryCertificationOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
