// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/LuckyMoneyGiftMeta.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.data;

/**
 * <p>LuckyMoneyGiftMetaOrBuilder interface.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public interface LuckyMoneyGiftMetaOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LuckyMoneyGiftMeta)
        com.google.protobuf.MessageOrBuilder {
}
