// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/TextPieceUser.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.data;

public final class TextPieceUserOuterClass {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TextPieceUser_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TextPieceUser_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n webcast/data/TextPieceUser.proto\032\027webc" +
                        "ast/data/User.proto\"7\n\rTextPieceUser\022\023\n\004" +
                        "user\030\001 \001(\0132\005.User\022\021\n\twithColon\030\002 \001(\010B?\n;" +
                        "cool.scx.live_room_watcher.douyin.proto_" +
                        "entity.webcast.dataP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.UserOuterClass.getDescriptor(),
                        });
        internal_static_TextPieceUser_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_TextPieceUser_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TextPieceUser_descriptor,
                new java.lang.String[]{"User", "WithColon",});
        cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.UserOuterClass.getDescriptor();
    }
    private TextPieceUserOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
