// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/TextPieceGift.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.data;

/**
 * <pre>
 * 更新时间 : 2023-01-05 17:22:10
 * </pre>
 * <p>
 * Protobuf type {@code TextPieceGift}
 *
 * @author scx567888
 * @version $Id: $Id
 */
public final class TextPieceGift extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TextPieceGift)
        TextPieceGiftOrBuilder {
    /**
     * Constant <code>GIFTID_FIELD_NUMBER=1</code>
     */
    public static final int GIFTID_FIELD_NUMBER = 1;
    // Use TextPieceGift.newBuilder() to construct.
    /**
     * Constant <code>NAMEREF_FIELD_NUMBER=2</code>
     */
    public static final int NAMEREF_FIELD_NUMBER = 2;
    /**
     * Constant <code>serialVersionUID=0L</code>
     */
    private static final long serialVersionUID = 0L;
    /**
     * Constant <code>DEFAULT_INSTANCE</code>
     */
    private static final cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift DEFAULT_INSTANCE;
    /**
     * Constant <code>PARSER</code>
     */
    private static final com.google.protobuf.Parser<TextPieceGift>
            PARSER = new com.google.protobuf.AbstractParser<TextPieceGift>() {
        @java.lang.Override
        public TextPieceGift parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new TextPieceGift(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift();
    }

    private long giftId_;
    private cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef nameRef_;
    private byte memoizedIsInitialized = -1;
    /**
     * <p>Constructor for TextPieceGift.</p>
     *
     * @param builder a {@link com.google.protobuf.GeneratedMessageV3.Builder} object
     */
    private TextPieceGift(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    /**
     * <p>Constructor for TextPieceGift.</p>
     */
    private TextPieceGift() {
    }

    /**
     * <p>Constructor for TextPieceGift.</p>
     *
     * @param input             a {@link com.google.protobuf.CodedInputStream} object
     * @param extensionRegistry a {@link com.google.protobuf.ExtensionRegistryLite} object
     * @throws com.google.protobuf.InvalidProtocolBufferException if any.
     */
    private TextPieceGift(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 8: {

                        giftId_ = input.readInt64();
                        break;
                    }
                    case 18: {
                        cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.Builder subBuilder = null;
                        if (nameRef_ != null) {
                            subBuilder = nameRef_.toBuilder();
                        }
                        nameRef_ = input.readMessage(cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(nameRef_);
                            nameRef_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    /**
     * <p>getDescriptor.</p>
     *
     * @return a {@link com.google.protobuf.Descriptors.Descriptor} object
     */
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGiftOuterClass.internal_static_TextPieceGift_descriptor;
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param data a {@link java.nio.ByteBuffer} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws com.google.protobuf.InvalidProtocolBufferException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param data              a {@link java.nio.ByteBuffer} object
     * @param extensionRegistry a {@link com.google.protobuf.ExtensionRegistryLite} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws com.google.protobuf.InvalidProtocolBufferException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param data a {@link com.google.protobuf.ByteString} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws com.google.protobuf.InvalidProtocolBufferException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param data              a {@link com.google.protobuf.ByteString} object
     * @param extensionRegistry a {@link com.google.protobuf.ExtensionRegistryLite} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws com.google.protobuf.InvalidProtocolBufferException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param data an array of {@link byte} objects
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws com.google.protobuf.InvalidProtocolBufferException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param data              an array of {@link byte} objects
     * @param extensionRegistry a {@link com.google.protobuf.ExtensionRegistryLite} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws com.google.protobuf.InvalidProtocolBufferException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param input a {@link java.io.InputStream} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws java.io.IOException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param input             a {@link java.io.InputStream} object
     * @param extensionRegistry a {@link com.google.protobuf.ExtensionRegistryLite} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws java.io.IOException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * <p>parseDelimitedFrom.</p>
     *
     * @param input a {@link java.io.InputStream} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws java.io.IOException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    /**
     * <p>parseDelimitedFrom.</p>
     *
     * @param input             a {@link java.io.InputStream} object
     * @param extensionRegistry a {@link com.google.protobuf.ExtensionRegistryLite} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws java.io.IOException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param input a {@link com.google.protobuf.CodedInputStream} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws java.io.IOException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    /**
     * <p>parseFrom.</p>
     *
     * @param input             a {@link com.google.protobuf.CodedInputStream} object
     * @param extensionRegistry a {@link com.google.protobuf.ExtensionRegistryLite} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @throws java.io.IOException if any.
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * <p>newBuilder.</p>
     *
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.Builder} object
     */
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    /**
     * <p>newBuilder.</p>
     *
     * @param prototype a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.Builder} object
     */
    public static Builder newBuilder(cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <p>getDefaultInstance.</p>
     *
     * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift} object
     */
    public static cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <p>parser.</p>
     *
     * @return a {@link com.google.protobuf.Parser} object
     */
    public static com.google.protobuf.Parser<TextPieceGift> parser() {
        return PARSER;
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new TextPieceGift();
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGiftOuterClass.internal_static_TextPieceGift_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.class, cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.Builder.class);
    }

    /**
     * {@inheritDoc}
     *
     * <code>int64 giftId = 1;</code>
     */
    @java.lang.Override
    public long getGiftId() {
        return giftId_;
    }

    /**
     * {@inheritDoc}
     *
     * <code>.PatternRef nameRef = 2;</code>
     */
    @java.lang.Override
    public boolean hasNameRef() {
        return nameRef_ != null;
    }

    /**
     * {@inheritDoc}
     *
     * <code>.PatternRef nameRef = 2;</code>
     */
    @java.lang.Override
    public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef getNameRef() {
        return nameRef_ == null ? cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.getDefaultInstance() : nameRef_;
    }

    /**
     * {@inheritDoc}
     *
     * <code>.PatternRef nameRef = 2;</code>
     */
    @java.lang.Override
    public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRefOrBuilder getNameRefOrBuilder() {
        return getNameRef();
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (giftId_ != 0L) {
            output.writeInt64(1, giftId_);
        }
        if (nameRef_ != null) {
            output.writeMessage(2, getNameRef());
        }
        unknownFields.writeTo(output);
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (giftId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, giftId_);
        }
        if (nameRef_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, getNameRef());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift)) {
            return super.equals(obj);
        }
        cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift other = (cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift) obj;

        if (getGiftId()
                != other.getGiftId()) return false;
        if (hasNameRef() != other.hasNameRef()) return false;
        if (hasNameRef()) {
            if (!getNameRef()
                    .equals(other.getNameRef())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    // @@protoc_insertion_point(class_scope:TextPieceGift)

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + GIFTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getGiftId());
        if (hasNameRef()) {
            hash = (37 * hash) + NAMEREF_FIELD_NUMBER;
            hash = (53 * hash) + getNameRef().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public com.google.protobuf.Parser<TextPieceGift> getParserForType() {
        return PARSER;
    }

    /**
     * {@inheritDoc}
     */
    @java.lang.Override
    public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * 更新时间 : 2023-01-05 17:22:10
     * </pre>
     * <p>
     * Protobuf type {@code TextPieceGift}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:TextPieceGift)
            cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGiftOrBuilder {
        private long giftId_;
        private cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef nameRef_;
        private com.google.protobuf.SingleFieldBuilderV3<
                cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef, cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.Builder, cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRefOrBuilder> nameRefBuilder_;

        // Construct using cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGiftOuterClass.internal_static_TextPieceGift_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGiftOuterClass.internal_static_TextPieceGift_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.class, cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            giftId_ = 0L;

            if (nameRefBuilder_ == null) {
                nameRef_ = null;
            } else {
                nameRef_ = null;
                nameRefBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGiftOuterClass.internal_static_TextPieceGift_descriptor;
        }

        @java.lang.Override
        public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift getDefaultInstanceForType() {
            return cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.getDefaultInstance();
        }

        @java.lang.Override
        public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift build() {
            cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift buildPartial() {
            cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift result = new cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift(this);
            result.giftId_ = giftId_;
            if (nameRefBuilder_ == null) {
                result.nameRef_ = nameRef_;
            } else {
                result.nameRef_ = nameRefBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift) {
                return mergeFrom((cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift other) {
            if (other == cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift.getDefaultInstance())
                return this;
            if (other.getGiftId() != 0L) {
                setGiftId(other.getGiftId());
            }
            if (other.hasNameRef()) {
                mergeNameRef(other.getNameRef());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.TextPieceGift) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int64 giftId = 1;</code>
         *
         * @return The giftId.
         */
        @java.lang.Override
        public long getGiftId() {
            return giftId_;
        }

        /**
         * <code>int64 giftId = 1;</code>
         *
         * @param value The giftId to set.
         * @return This builder for chaining.
         */
        public Builder setGiftId(long value) {

            giftId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 giftId = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearGiftId() {

            giftId_ = 0L;
            onChanged();
            return this;
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         *
         * @return Whether the nameRef field is set.
         */
        public boolean hasNameRef() {
            return nameRefBuilder_ != null || nameRef_ != null;
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         *
         * @return The nameRef.
         */
        public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef getNameRef() {
            if (nameRefBuilder_ == null) {
                return nameRef_ == null ? cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.getDefaultInstance() : nameRef_;
            } else {
                return nameRefBuilder_.getMessage();
            }
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         */
        public Builder setNameRef(cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef value) {
            if (nameRefBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                nameRef_ = value;
                onChanged();
            } else {
                nameRefBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         */
        public Builder setNameRef(
                cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.Builder builderForValue) {
            if (nameRefBuilder_ == null) {
                nameRef_ = builderForValue.build();
                onChanged();
            } else {
                nameRefBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         */
        public Builder mergeNameRef(cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef value) {
            if (nameRefBuilder_ == null) {
                if (nameRef_ != null) {
                    nameRef_ =
                            cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.newBuilder(nameRef_).mergeFrom(value).buildPartial();
                } else {
                    nameRef_ = value;
                }
                onChanged();
            } else {
                nameRefBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         */
        public Builder clearNameRef() {
            if (nameRefBuilder_ == null) {
                nameRef_ = null;
                onChanged();
            } else {
                nameRef_ = null;
                nameRefBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         */
        public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.Builder getNameRefBuilder() {

            onChanged();
            return getNameRefFieldBuilder().getBuilder();
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         */
        public cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRefOrBuilder getNameRefOrBuilder() {
            if (nameRefBuilder_ != null) {
                return nameRefBuilder_.getMessageOrBuilder();
            } else {
                return nameRef_ == null ?
                        cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.getDefaultInstance() : nameRef_;
            }
        }

        /**
         * <code>.PatternRef nameRef = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef, cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.Builder, cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRefOrBuilder>
        getNameRefFieldBuilder() {
            if (nameRefBuilder_ == null) {
                nameRefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef, cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRef.Builder, cool.scx.live_room_watcher.douyin.proto_entity.webcast.data.PatternRefOrBuilder>(
                        getNameRef(),
                        getParentForChildren(),
                        isClean());
                nameRef_ = null;
            }
            return nameRefBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:TextPieceGift)
    }

}

