// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/Decoration.proto

package cool.scx.live_room_watcher.douyin_hack.proto_entity.webcast.data;

public interface DecorationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Decoration)
    com.google.protobuf.MessageOrBuilder {
}
