// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/EffectMixImageInfo.proto

package cool.scx.live_room_watcher.douyin_hack.proto_entity.webcast.data;

public interface EffectMixImageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EffectMixImageInfo)
    com.google.protobuf.MessageOrBuilder {
}
