// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok_hack/pushproto/TPushFrame.proto
// Protobuf Java Version: 4.26.0

package cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.pushproto;

public final class TPushFrameOuterClass {
  private TPushFrameOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      TPushFrameOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TPushFrame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TPushFrame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&tiktok_hack/pushproto/TPushFrame.proto" +
      "\032\'tiktok_hack/pushproto/TPushHeader.prot" +
      "o\"\255\001\n\nTPushFrame\022\r\n\005seqid\030\001 \001(\004\022\r\n\005logid" +
      "\030\002 \001(\004\022\017\n\007service\030\003 \001(\004\022\016\n\006method\030\004 \001(\004\022" +
      "!\n\013headersList\030\005 \003(\0132\014.TPushHeader\022\027\n\017pa" +
      "yloadEncoding\030\006 \001(\t\022\023\n\013payloadType\030\007 \001(\t" +
      "\022\017\n\007payload\030\010 \001(\014BF\nBcool.scx.live_room_" +
      "watcher.impl.tiktok_hack.proto_entity.pu" +
      "shprotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.pushproto.TPushHeaderOuterClass.getDescriptor(),
        });
    internal_static_TPushFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TPushFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TPushFrame_descriptor,
        new java.lang.String[] { "Seqid", "Logid", "Service", "Method", "HeadersList", "PayloadEncoding", "PayloadType", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
    cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.pushproto.TPushHeaderOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
