// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok_hack/webcast/data/LiveMessageID.proto

// Protobuf Java Version: 4.26.1
package cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.data;

public interface LiveMessageIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tiktok_hack.LiveMessageID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string primaryId = 1;</code>
   * @return The primaryId.
   */
  java.lang.String getPrimaryId();
  /**
   * <code>string primaryId = 1;</code>
   * @return The bytes for primaryId.
   */
  com.google.protobuf.ByteString
      getPrimaryIdBytes();

  /**
   * <code>string messageScene = 2;</code>
   * @return The messageScene.
   */
  java.lang.String getMessageScene();
  /**
   * <code>string messageScene = 2;</code>
   * @return The bytes for messageScene.
   */
  com.google.protobuf.ByteString
      getMessageSceneBytes();
}
