// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tiktok_hack/webcast/im/GiftMessage.proto
// Protobuf Java Version: 4.27.3

package cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.im;

public final class GiftMessageOuterClass {
  private GiftMessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      GiftMessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tiktok_hack_GiftMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tiktok_hack_GiftMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(tiktok_hack/webcast/im/GiftMessage.pro" +
      "to\022\013tiktok_hack\032#tiktok_hack/webcast/im/" +
      "Common.proto\032#tiktok_hack/webcast/data/U" +
      "ser.proto\032)tiktok_hack/webcast/data/Gift" +
      "Struct.proto\"\202\002\n\013GiftMessage\022#\n\006common\030\001" +
      " \001(\0132\023.tiktok_hack.Common\022\016\n\006giftId\030\002 \001(" +
      "\t\022\026\n\016fanTicketCount\030\003 \001(\003\022\022\n\ngroupCount\030" +
      "\004 \001(\003\022\023\n\013repeatCount\030\005 \001(\003\022\022\n\ncomboCount" +
      "\030\006 \001(\003\022\037\n\004user\030\007 \001(\0132\021.tiktok_hack.User\022" +
      "!\n\006toUser\030\010 \001(\0132\021.tiktok_hack.User\022%\n\004gi" +
      "ft\030\017 \001(\0132\027.tiktok_hack.GiftStructBG\nCcoo" +
      "l.scx.live_room_watcher.impl.tiktok_hack" +
      ".proto_entity.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.im.CommonOuterClass.getDescriptor(),
          cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.data.UserOuterClass.getDescriptor(),
          cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.data.GiftStructOuterClass.getDescriptor(),
        });
    internal_static_tiktok_hack_GiftMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tiktok_hack_GiftMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tiktok_hack_GiftMessage_descriptor,
        new java.lang.String[] { "Common", "GiftId", "FanTicketCount", "GroupCount", "RepeatCount", "ComboCount", "User", "ToUser", "Gift", });
    descriptor.resolveAllFeaturesImmutable();
    cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.im.CommonOuterClass.getDescriptor();
    cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.data.UserOuterClass.getDescriptor();
    cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.data.GiftStructOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
