// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tiktok_hack/webcast/im/PublicAreaCommon.proto
// Protobuf Java Version: 4.27.0

package cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.im;

public interface PublicAreaCommonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tiktok_hack.PublicAreaCommon)
    com.google.protobuf.MessageOrBuilder {
}
