// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tiktok_hack/webcast/im/SpecifiedDisplayText.proto

// Protobuf Java Version: 4.26.1
package cool.scx.live_room_watcher.impl.tiktok_hack.proto_entity.webcast.im;

public interface SpecifiedDisplayTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tiktok_hack.SpecifiedDisplayText)
    com.google.protobuf.MessageOrBuilder {
}
