// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: douyin_hack/webcast/im/InRoomBannerMessage.proto
// Protobuf Java Version: 4.32.1

package cool.scx.live_room_watcher.impl.douyin_hack.proto.webcast.im;

@com.google.protobuf.Generated
public final class InRoomBannerMessageOuterClass extends com.google.protobuf.GeneratedFile {
  private InRoomBannerMessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      InRoomBannerMessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcast_im_InRoomBannerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webcast_im_InRoomBannerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0douyin_hack/webcast/im/InRoomBannerMes" +
      "sage.proto\022\nwebcast.im\032#douyin_hack/webc" +
      "ast/im/Common.proto\"9\n\023InRoomBannerMessa" +
      "ge\022\"\n\006common\030\001 \001(\0132\022.webcast.im.CommonB@" +
      "\n<cool.scx.live_room_watcher.impl.douyin" +
      "_hack.proto.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cool.scx.live_room_watcher.impl.douyin_hack.proto.webcast.im.CommonOuterClass.getDescriptor(),
        });
    internal_static_webcast_im_InRoomBannerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webcast_im_InRoomBannerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webcast_im_InRoomBannerMessage_descriptor,
        new java.lang.String[] { "Common", });
    descriptor.resolveAllFeaturesImmutable();
    cool.scx.live_room_watcher.impl.douyin_hack.proto.webcast.im.CommonOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
