// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/AnchorUpdateLayoutContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>AnchorUpdateLayoutContentOuterClass class.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public final class AnchorUpdateLayoutContentOuterClass {
    /**
     * Constant <code>internal_static_AnchorUpdateLayoutContent_descriptor</code>
     */
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_AnchorUpdateLayoutContent_descriptor;
    /**
     * Constant <code>internal_static_AnchorUpdateLayoutContent_fieldAccessorTable</code>
     */
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_AnchorUpdateLayoutContent_fieldAccessorTable;
    /**
     * Constant <code>descriptor</code>
     */
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n*webcast/im/AnchorUpdateLayoutContent.p" +
                        "roto\"\033\n\031AnchorUpdateLayoutContentB=\n9coo" +
                        "l.scx.live_room_watcher.douyin.proto_ent" +
                        "ity.webcast.imP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_AnchorUpdateLayoutContent_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_AnchorUpdateLayoutContent_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_AnchorUpdateLayoutContent_descriptor,
                new java.lang.String[]{});
    }
    /**
     * <p>Constructor for AnchorUpdateLayoutContentOuterClass.</p>
     */
    private AnchorUpdateLayoutContentOuterClass() {
    }

    /**
     * <p>registerAllExtensions.</p>
     *
     * @param registry a {@link com.google.protobuf.ExtensionRegistryLite} object
     */
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    /**
     * <p>registerAllExtensions.</p>
     *
     * @param registry a {@link com.google.protobuf.ExtensionRegistry} object
     */
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * <p>Getter for the field <code>descriptor</code>.</p>
     *
     * @return a {@link com.google.protobuf.Descriptors.FileDescriptor} object
     */
    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
