// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/CrossRoomRTCInfoContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

public final class CrossRoomRTCInfoContentOuterClass {
  private CrossRoomRTCInfoContentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CrossRoomRTCInfoContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CrossRoomRTCInfoContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(webcast/im/CrossRoomRTCInfoContent.pro" +
      "to\"\031\n\027CrossRoomRTCInfoContentB=\n9cool.sc" +
      "x.live_room_watcher.douyin.proto_entity." +
      "webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CrossRoomRTCInfoContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CrossRoomRTCInfoContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CrossRoomRTCInfoContent_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
