// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/CrossRoomRTCInfoContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

public interface CrossRoomRTCInfoContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CrossRoomRTCInfoContent)
    com.google.protobuf.MessageOrBuilder {
}
