// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/CrossRoomLinkCancelInviteContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>CrossRoomLinkCancelInviteContentOuterClass class.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public final class CrossRoomLinkCancelInviteContentOuterClass {
  /**
   * <p>Constructor for CrossRoomLinkCancelInviteContentOuterClass.</p>
   */
  private CrossRoomLinkCancelInviteContentOuterClass() {}
  /**
   * <p>registerAllExtensions.</p>
   *
   * @param registry a {@link com.google.protobuf.ExtensionRegistryLite} object
   */
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  /**
   * <p>registerAllExtensions.</p>
   *
   * @param registry a {@link com.google.protobuf.ExtensionRegistry} object
   */
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /** Constant <code>internal_static_CrossRoomLinkCancelInviteContent_descriptor</code> */
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CrossRoomLinkCancelInviteContent_descriptor;
  /** Constant <code>internal_static_CrossRoomLinkCancelInviteContent_fieldAccessorTable</code> */
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CrossRoomLinkCancelInviteContent_fieldAccessorTable;

  /**
   * <p>Getter for the field <code>descriptor</code>.</p>
   *
   * @return a {@link com.google.protobuf.Descriptors.FileDescriptor} object
   */
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  /** Constant <code>descriptor</code> */
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1webcast/im/CrossRoomLinkCancelInviteCo" +
      "ntent.proto\"\"\n CrossRoomLinkCancelInvite" +
      "ContentB=\n9cool.scx.live_room_watcher.do" +
      "uyin.proto_entity.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CrossRoomLinkCancelInviteContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CrossRoomLinkCancelInviteContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CrossRoomLinkCancelInviteContent_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
