// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/CrossRoomLinkReplyContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>CrossRoomLinkReplyContentOrBuilder interface.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public interface CrossRoomLinkReplyContentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CrossRoomLinkReplyContent)
        com.google.protobuf.MessageOrBuilder {
}
