// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/DisplayControlInfo.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>DisplayControlInfoOrBuilder interface.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public interface DisplayControlInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:DisplayControlInfo)
        com.google.protobuf.MessageOrBuilder {
}
