// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LinkerUpdateUserContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>LinkerUpdateUserContentOrBuilder interface.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public interface LinkerUpdateUserContentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LinkerUpdateUserContent)
        com.google.protobuf.MessageOrBuilder {
}
