// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LinkerBanContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>LinkerBanContentOuterClass class.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public final class LinkerBanContentOuterClass {
    /**
     * Constant <code>internal_static_LinkerBanContent_descriptor</code>
     */
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LinkerBanContent_descriptor;
    /**
     * Constant <code>internal_static_LinkerBanContent_fieldAccessorTable</code>
     */
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LinkerBanContent_fieldAccessorTable;
    /**
     * Constant <code>descriptor</code>
     */
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n!webcast/im/LinkerBanContent.proto\"\022\n\020L" +
                        "inkerBanContentB=\n9cool.scx.live_room_wa" +
                        "tcher.douyin.proto_entity.webcast.imP\001b\006" +
                        "proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_LinkerBanContent_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_LinkerBanContent_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LinkerBanContent_descriptor,
                new java.lang.String[]{});
    }
    /**
     * <p>Constructor for LinkerBanContentOuterClass.</p>
     */
    private LinkerBanContentOuterClass() {
    }

    /**
     * <p>registerAllExtensions.</p>
     *
     * @param registry a {@link com.google.protobuf.ExtensionRegistryLite} object
     */
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    /**
     * <p>registerAllExtensions.</p>
     *
     * @param registry a {@link com.google.protobuf.ExtensionRegistry} object
     */
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * <p>Getter for the field <code>descriptor</code>.</p>
     *
     * @return a {@link com.google.protobuf.Descriptors.FileDescriptor} object
     */
    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
