// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LinkerUpdateLinkTypeReplyContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

public final class LinkerUpdateLinkTypeReplyContentOuterClass {
  private LinkerUpdateLinkTypeReplyContentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LinkerUpdateLinkTypeReplyContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LinkerUpdateLinkTypeReplyContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1webcast/im/LinkerUpdateLinkTypeReplyCo" +
      "ntent.proto\"\"\n LinkerUpdateLinkTypeReply" +
      "ContentB=\n9cool.scx.live_room_watcher.do" +
      "uyin.proto_entity.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LinkerUpdateLinkTypeReplyContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LinkerUpdateLinkTypeReplyContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LinkerUpdateLinkTypeReplyContent_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
