// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LinkerEnlargeGuestApplyContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>LinkerEnlargeGuestApplyContentOrBuilder interface.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public interface LinkerEnlargeGuestApplyContentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LinkerEnlargeGuestApplyContent)
        com.google.protobuf.MessageOrBuilder {
}
