// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LinkerDegradeAlertContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>LinkerDegradeAlertContentOuterClass class.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public final class LinkerDegradeAlertContentOuterClass {
  /**
   * <p>Constructor for LinkerDegradeAlertContentOuterClass.</p>
   */
  private LinkerDegradeAlertContentOuterClass() {}
  /**
   * <p>registerAllExtensions.</p>
   *
   * @param registry a {@link com.google.protobuf.ExtensionRegistryLite} object
   */
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  /**
   * <p>registerAllExtensions.</p>
   *
   * @param registry a {@link com.google.protobuf.ExtensionRegistry} object
   */
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /** Constant <code>internal_static_LinkerDegradeAlertContent_descriptor</code> */
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LinkerDegradeAlertContent_descriptor;
  /** Constant <code>internal_static_LinkerDegradeAlertContent_fieldAccessorTable</code> */
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LinkerDegradeAlertContent_fieldAccessorTable;

  /**
   * <p>Getter for the field <code>descriptor</code>.</p>
   *
   * @return a {@link com.google.protobuf.Descriptors.FileDescriptor} object
   */
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  /** Constant <code>descriptor</code> */
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*webcast/im/LinkerDegradeAlertContent.p" +
      "roto\"\033\n\031LinkerDegradeAlertContentB=\n9coo" +
      "l.scx.live_room_watcher.douyin.proto_ent" +
      "ity.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LinkerDegradeAlertContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LinkerDegradeAlertContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LinkerDegradeAlertContent_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
