// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LinkerWaitingListChangeContent.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

public interface LinkerWaitingListChangeContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkerWaitingListChangeContent)
    com.google.protobuf.MessageOrBuilder {
}
