// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/Message.proto

package cool.scx.live_room_watcher.douyin.proto_entity.webcast.im;

/**
 * <p>MessageOuterClass class.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public final class MessageOuterClass {
  /**
   * <p>Constructor for MessageOuterClass.</p>
   */
  private MessageOuterClass() {}
  /**
   * <p>registerAllExtensions.</p>
   *
   * @param registry a {@link com.google.protobuf.ExtensionRegistryLite} object
   */
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  /**
   * <p>registerAllExtensions.</p>
   *
   * @param registry a {@link com.google.protobuf.ExtensionRegistry} object
   */
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /** Constant <code>internal_static_Message_descriptor</code> */
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  /** Constant <code>internal_static_Message_fieldAccessorTable</code> */
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  /** Constant <code>internal_static_Message_MessageExtraMapEntry_descriptor</code> */
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_MessageExtraMapEntry_descriptor;
  /** Constant <code>internal_static_Message_MessageExtraMapEntry_fieldAccessorTable</code> */
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_MessageExtraMapEntry_fieldAccessorTable;

  /**
   * <p>Getter for the field <code>descriptor</code>.</p>
   *
   * @return a {@link com.google.protobuf.Descriptors.FileDescriptor} object
   */
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  /** Constant <code>descriptor</code> */
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030webcast/im/Message.proto\"\212\002\n\007Message\022\016" +
      "\n\006method\030\001 \001(\t\022\017\n\007payload\030\002 \001(\014\022\r\n\005msgId" +
      "\030\003 \001(\003\022\017\n\007msgType\030\004 \001(\005\022\016\n\006offset\030\005 \001(\003\022" +
      "\025\n\rneedWrdsStore\030\006 \001(\010\022\023\n\013wrdsVersion\030\007 " +
      "\001(\003\022\022\n\nwrdsSubKey\030\010 \001(\t\0226\n\017messageExtraM" +
      "ap\030\t \003(\0132\035.Message.MessageExtraMapEntry\032" +
      "6\n\024MessageExtraMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001B=\n9cool.scx.live_room_wa" +
      "tcher.douyin.proto_entity.webcast.imP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Method", "Payload", "MsgId", "MsgType", "Offset", "NeedWrdsStore", "WrdsVersion", "WrdsSubKey", "MessageExtraMap", });
    internal_static_Message_MessageExtraMapEntry_descriptor =
      internal_static_Message_descriptor.getNestedTypes().get(0);
    internal_static_Message_MessageExtraMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_MessageExtraMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
