// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/GiftBanner.proto

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data;

public final class GiftBannerOuterClass {
  private GiftBannerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GiftBanner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GiftBanner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035webcast/data/GiftBanner.proto\"\014\n\nGiftB" +
      "annerBI\nEcool.scx.live_room_watcher.impl" +
      ".douyin_hack.proto_entity.webcast.dataP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GiftBanner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GiftBanner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GiftBanner_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
