// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: douyin_hack/webcast/data/TextPieceImage.proto
// Protobuf Java Version: 4.27.1

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data;

public interface TextPieceImageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextPieceImage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Image image = 1;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <code>.Image image = 1;</code>
   * @return The image.
   */
  cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image getImage();
  /**
   * <code>.Image image = 1;</code>
   */
  cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.ImageOrBuilder getImageOrBuilder();

  /**
   * <code>float scalingRate = 2;</code>
   * @return The scalingRate.
   */
  float getScalingRate();
}
