// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/data/TextPieceGift.proto

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data;

public final class TextPieceGiftOuterClass {
  private TextPieceGiftOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextPieceGift_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextPieceGift_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n webcast/data/TextPieceGift.proto\032\035webc" +
      "ast/data/PatternRef.proto\"=\n\rTextPieceGi" +
      "ft\022\016\n\006giftId\030\001 \001(\003\022\034\n\007nameRef\030\002 \001(\0132\013.Pa" +
      "tternRefBI\nEcool.scx.live_room_watcher.i" +
      "mpl.douyin_hack.proto_entity.webcast.dat" +
      "aP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.PatternRefOuterClass.getDescriptor(),
        });
    internal_static_TextPieceGift_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TextPieceGift_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextPieceGift_descriptor,
        new java.lang.String[] { "GiftId", "NameRef", });
    cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.PatternRefOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
