// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: douyin_hack/webcast/data/Text.proto
// Protobuf Java Version: 4.32.1

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data;

@com.google.protobuf.Generated
public final class TextOuterClass extends com.google.protobuf.GeneratedFile {
  private TextOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      TextOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcast_data_Text_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webcast_data_Text_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#douyin_hack/webcast/data/Text.proto\022\014w" +
      "ebcast.data\",\n\004Text\022\013\n\003key\030\001 \001(\t\022\027\n\017defa" +
      "ult_pattern\030\002 \001(\tBI\nEcool.scx.live_room_" +
      "watcher.impl.douyin_hack.proto_entity.we" +
      "bcast.dataP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_webcast_data_Text_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webcast_data_Text_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webcast_data_Text_descriptor,
        new java.lang.String[] { "Key", "DefaultPattern", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
