// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin_hack/webcast/data/TextPieceGift.proto

// Protobuf Java Version: 3.25.1
package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data;

public final class TextPieceGiftOuterClass {
  private TextPieceGiftOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextPieceGift_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextPieceGift_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,douyin_hack/webcast/data/TextPieceGift" +
      ".proto\032)douyin_hack/webcast/data/Pattern" +
      "Ref.proto\"=\n\rTextPieceGift\022\016\n\006giftId\030\001 \001" +
      "(\003\022\034\n\007nameRef\030\002 \001(\0132\013.PatternRefBI\nEcool" +
      ".scx.live_room_watcher.impl.douyin_hack." +
      "proto_entity.webcast.dataP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.PatternRefOuterClass.getDescriptor(),
        });
    internal_static_TextPieceGift_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TextPieceGift_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextPieceGift_descriptor,
        new java.lang.String[] { "GiftId", "NameRef", });
    cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.PatternRefOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
