// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushproto/PushFrame.proto

package cool.scx.live_room_watcher.douyin.proto_entity.pushproto;

/**
 * <p>PushFrameOrBuilder interface.</p>
 *
 * @author scx567888
 * @version $Id: $Id
 */
public interface PushFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PushFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 seqid = 1;</code>
   *
   * @return The seqid.
   */
  long getSeqid();

  /**
   * <code>uint64 logid = 2;</code>
   *
   * @return The logid.
   */
  long getLogid();

  /**
   * <code>uint64 service = 3;</code>
   *
   * @return The service.
   */
  long getService();

  /**
   * <code>uint64 method = 4;</code>
   *
   * @return The method.
   */
  long getMethod();

      /**
       * <code>repeated .PushHeader headersList = 5;</code>
       *
       * @return a {@link java.util.List} object
       */
  java.util.List<cool.scx.live_room_watcher.douyin.proto_entity.pushproto.PushHeader>
      getHeadersListList();
  /**
   * <code>repeated .PushHeader headersList = 5;</code>
   *
   * @param index a int
   * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.pushproto.PushHeader} object
   */
  cool.scx.live_room_watcher.douyin.proto_entity.pushproto.PushHeader getHeadersList(int index);
  /**
   * <code>repeated .PushHeader headersList = 5;</code>
   *
   * @return a int
   */
  int getHeadersListCount();
      /**
       * <code>repeated .PushHeader headersList = 5;</code>
       *
       * @return a {@link java.util.List} object
       */
  java.util.List<? extends cool.scx.live_room_watcher.douyin.proto_entity.pushproto.PushHeaderOrBuilder>
      getHeadersListOrBuilderList();
  /**
   * <code>repeated .PushHeader headersList = 5;</code>
   *
   * @param index a int
   * @return a {@link cool.scx.live_room_watcher.douyin.proto_entity.pushproto.PushHeaderOrBuilder} object
   */
  cool.scx.live_room_watcher.douyin.proto_entity.pushproto.PushHeaderOrBuilder getHeadersListOrBuilder(
      int index);

  /**
   * <code>string payloadEncoding = 6;</code>
   *
   * @return The payloadEncoding.
   */
  java.lang.String getPayloadEncoding();
      /**
       * <code>string payloadEncoding = 6;</code>
       *
       * @return The bytes for payloadEncoding.
       */
  com.google.protobuf.ByteString
      getPayloadEncodingBytes();

  /**
   * <code>string payloadType = 7;</code>
   *
   * @return The payloadType.
   */
  java.lang.String getPayloadType();
      /**
       * <code>string payloadType = 7;</code>
       *
       * @return The bytes for payloadType.
       */
  com.google.protobuf.ByteString
      getPayloadTypeBytes();

  /**
   * <code>bytes payload = 8;</code>
   *
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
