// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin_hack/webcast/im/AnchorUpdateLinkmicConfigContent.proto

// Protobuf Java Version: 3.25.1
package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public interface AnchorUpdateLinkmicConfigContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnchorUpdateLinkmicConfigContent)
    com.google.protobuf.MessageOrBuilder {
}
