// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: douyin_hack/webcast/im/ChatMessage.proto
// Protobuf Java Version: 4.32.1

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

@com.google.protobuf.Generated
public final class ChatMessageOuterClass extends com.google.protobuf.GeneratedFile {
  private ChatMessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      ChatMessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcast_im_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webcast_im_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(douyin_hack/webcast/im/ChatMessage.pro" +
      "to\022\nwebcast.im\032#douyin_hack/webcast/data" +
      "/User.proto\032#douyin_hack/webcast/im/Comm" +
      "on.proto\"d\n\013ChatMessage\022\"\n\006common\030\001 \001(\0132" +
      "\022.webcast.im.Common\022 \n\004user\030\002 \001(\0132\022.webc" +
      "ast.data.User\022\017\n\007content\030\003 \001(\tBG\nCcool.s" +
      "cx.live_room_watcher.impl.douyin_hack.pr" +
      "oto_entity.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOuterClass.getDescriptor(),
          cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOuterClass.getDescriptor(),
        });
    internal_static_webcast_im_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webcast_im_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webcast_im_ChatMessage_descriptor,
        new java.lang.String[] { "Common", "User", "Content", });
    descriptor.resolveAllFeaturesImmutable();
    cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOuterClass.getDescriptor();
    cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
