// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: douyin_hack/webcast/im/EmojiChatMessage.proto
// Protobuf Java Version: 4.27.1

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

/**
 * <pre>
 * 更新时间 : 2023-01-11
 * </pre>
 *
 * Protobuf type {@code EmojiChatMessage}
 */
public final class EmojiChatMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:EmojiChatMessage)
    EmojiChatMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      EmojiChatMessage.class.getName());
  }
  // Use EmojiChatMessage.newBuilder() to construct.
  private EmojiChatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EmojiChatMessage() {
    defaultContent_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessageOuterClass.internal_static_EmojiChatMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessageOuterClass.internal_static_EmojiChatMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage.class, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage.Builder.class);
  }

  private int bitField0_;
  public static final int COMMON_FIELD_NUMBER = 1;
  private cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common common_;
  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  @java.lang.Override
  public boolean hasCommon() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common getCommon() {
    return common_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.getDefaultInstance() : common_;
  }
  /**
   * <code>.Common common = 1;</code>
   */
  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOrBuilder getCommonOrBuilder() {
    return common_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.getDefaultInstance() : common_;
  }

  public static final int USER_FIELD_NUMBER = 2;
  private cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User user_;
  /**
   * <code>.User user = 2;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.User user = 2;</code>
   * @return The user.
   */
  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User getUser() {
    return user_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.User user = 2;</code>
   */
  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOrBuilder getUserOrBuilder() {
    return user_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.getDefaultInstance() : user_;
  }

  public static final int EMOJIID_FIELD_NUMBER = 3;
  private long emojiId_ = 0L;
  /**
   * <code>int64 emojiId = 3;</code>
   * @return The emojiId.
   */
  @java.lang.Override
  public long getEmojiId() {
    return emojiId_;
  }

  public static final int EMOJICONTENT_FIELD_NUMBER = 4;
  private cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text emojiContent_;
  /**
   * <code>.Text emojiContent = 4;</code>
   * @return Whether the emojiContent field is set.
   */
  @java.lang.Override
  public boolean hasEmojiContent() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.Text emojiContent = 4;</code>
   * @return The emojiContent.
   */
  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text getEmojiContent() {
    return emojiContent_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.getDefaultInstance() : emojiContent_;
  }
  /**
   * <code>.Text emojiContent = 4;</code>
   */
  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.TextOrBuilder getEmojiContentOrBuilder() {
    return emojiContent_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.getDefaultInstance() : emojiContent_;
  }

  public static final int DEFAULTCONTENT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object defaultContent_ = "";
  /**
   * <code>string defaultContent = 5;</code>
   * @return The defaultContent.
   */
  @java.lang.Override
  public java.lang.String getDefaultContent() {
    java.lang.Object ref = defaultContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      defaultContent_ = s;
      return s;
    }
  }
  /**
   * <code>string defaultContent = 5;</code>
   * @return The bytes for defaultContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDefaultContentBytes() {
    java.lang.Object ref = defaultContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      defaultContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BACKGROUNDIMAGE_FIELD_NUMBER = 6;
  private cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image backgroundImage_;
  /**
   * <code>.Image backgroundImage = 6;</code>
   * @return Whether the backgroundImage field is set.
   */
  @java.lang.Override
  public boolean hasBackgroundImage() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.Image backgroundImage = 6;</code>
   * @return The backgroundImage.
   */
  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image getBackgroundImage() {
    return backgroundImage_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.getDefaultInstance() : backgroundImage_;
  }
  /**
   * <code>.Image backgroundImage = 6;</code>
   */
  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.ImageOrBuilder getBackgroundImageOrBuilder() {
    return backgroundImage_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.getDefaultInstance() : backgroundImage_;
  }

  public static final int FROMINTERCOM_FIELD_NUMBER = 7;
  private boolean fromIntercom_ = false;
  /**
   * <code>bool fromIntercom = 7;</code>
   * @return The fromIntercom.
   */
  @java.lang.Override
  public boolean getFromIntercom() {
    return fromIntercom_;
  }

  public static final int INTERCOMHIDEUSERCARD_FIELD_NUMBER = 8;
  private boolean intercomHideUserCard_ = false;
  /**
   * <code>bool intercomHideUserCard = 8;</code>
   * @return The intercomHideUserCard.
   */
  @java.lang.Override
  public boolean getIntercomHideUserCard() {
    return intercomHideUserCard_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCommon());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getUser());
    }
    if (emojiId_ != 0L) {
      output.writeInt64(3, emojiId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getEmojiContent());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(defaultContent_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, defaultContent_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(6, getBackgroundImage());
    }
    if (fromIntercom_ != false) {
      output.writeBool(7, fromIntercom_);
    }
    if (intercomHideUserCard_ != false) {
      output.writeBool(8, intercomHideUserCard_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommon());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUser());
    }
    if (emojiId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, emojiId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEmojiContent());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(defaultContent_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, defaultContent_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getBackgroundImage());
    }
    if (fromIntercom_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, fromIntercom_);
    }
    if (intercomHideUserCard_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, intercomHideUserCard_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage)) {
      return super.equals(obj);
    }
    cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage other = (cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage) obj;

    if (hasCommon() != other.hasCommon()) return false;
    if (hasCommon()) {
      if (!getCommon()
          .equals(other.getCommon())) return false;
    }
    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (getEmojiId()
        != other.getEmojiId()) return false;
    if (hasEmojiContent() != other.hasEmojiContent()) return false;
    if (hasEmojiContent()) {
      if (!getEmojiContent()
          .equals(other.getEmojiContent())) return false;
    }
    if (!getDefaultContent()
        .equals(other.getDefaultContent())) return false;
    if (hasBackgroundImage() != other.hasBackgroundImage()) return false;
    if (hasBackgroundImage()) {
      if (!getBackgroundImage()
          .equals(other.getBackgroundImage())) return false;
    }
    if (getFromIntercom()
        != other.getFromIntercom()) return false;
    if (getIntercomHideUserCard()
        != other.getIntercomHideUserCard()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommon()) {
      hash = (37 * hash) + COMMON_FIELD_NUMBER;
      hash = (53 * hash) + getCommon().hashCode();
    }
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (37 * hash) + EMOJIID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEmojiId());
    if (hasEmojiContent()) {
      hash = (37 * hash) + EMOJICONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getEmojiContent().hashCode();
    }
    hash = (37 * hash) + DEFAULTCONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultContent().hashCode();
    if (hasBackgroundImage()) {
      hash = (37 * hash) + BACKGROUNDIMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getBackgroundImage().hashCode();
    }
    hash = (37 * hash) + FROMINTERCOM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFromIntercom());
    hash = (37 * hash) + INTERCOMHIDEUSERCARD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIntercomHideUserCard());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 更新时间 : 2023-01-11
   * </pre>
   *
   * Protobuf type {@code EmojiChatMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmojiChatMessage)
      cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessageOuterClass.internal_static_EmojiChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessageOuterClass.internal_static_EmojiChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage.class, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage.Builder.class);
    }

    // Construct using cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getCommonFieldBuilder();
        getUserFieldBuilder();
        getEmojiContentFieldBuilder();
        getBackgroundImageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      emojiId_ = 0L;
      emojiContent_ = null;
      if (emojiContentBuilder_ != null) {
        emojiContentBuilder_.dispose();
        emojiContentBuilder_ = null;
      }
      defaultContent_ = "";
      backgroundImage_ = null;
      if (backgroundImageBuilder_ != null) {
        backgroundImageBuilder_.dispose();
        backgroundImageBuilder_ = null;
      }
      fromIntercom_ = false;
      intercomHideUserCard_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessageOuterClass.internal_static_EmojiChatMessage_descriptor;
    }

    @java.lang.Override
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage getDefaultInstanceForType() {
      return cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage.getDefaultInstance();
    }

    @java.lang.Override
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage build() {
      cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage buildPartial() {
      cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage result = new cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.common_ = commonBuilder_ == null
            ? common_
            : commonBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.user_ = userBuilder_ == null
            ? user_
            : userBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.emojiId_ = emojiId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.emojiContent_ = emojiContentBuilder_ == null
            ? emojiContent_
            : emojiContentBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.defaultContent_ = defaultContent_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.backgroundImage_ = backgroundImageBuilder_ == null
            ? backgroundImage_
            : backgroundImageBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.fromIntercom_ = fromIntercom_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.intercomHideUserCard_ = intercomHideUserCard_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage) {
        return mergeFrom((cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage other) {
      if (other == cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage.getDefaultInstance()) return this;
      if (other.hasCommon()) {
        mergeCommon(other.getCommon());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.getEmojiId() != 0L) {
        setEmojiId(other.getEmojiId());
      }
      if (other.hasEmojiContent()) {
        mergeEmojiContent(other.getEmojiContent());
      }
      if (!other.getDefaultContent().isEmpty()) {
        defaultContent_ = other.defaultContent_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasBackgroundImage()) {
        mergeBackgroundImage(other.getBackgroundImage());
      }
      if (other.getFromIntercom() != false) {
        setFromIntercom(other.getFromIntercom());
      }
      if (other.getIntercomHideUserCard() != false) {
        setIntercomHideUserCard(other.getIntercomHideUserCard());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCommonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              emojiId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getEmojiContentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              defaultContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getBackgroundImageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              fromIntercom_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              intercomHideUserCard_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common common_;
    private com.google.protobuf.SingleFieldBuilder<
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOrBuilder> commonBuilder_;
    /**
     * <code>.Common common = 1;</code>
     * @return Whether the common field is set.
     */
    public boolean hasCommon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Common common = 1;</code>
     * @return The common.
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common getCommon() {
      if (commonBuilder_ == null) {
        return common_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.getDefaultInstance() : common_;
      } else {
        return commonBuilder_.getMessage();
      }
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public Builder setCommon(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common value) {
      if (commonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        common_ = value;
      } else {
        commonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public Builder setCommon(
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.Builder builderForValue) {
      if (commonBuilder_ == null) {
        common_ = builderForValue.build();
      } else {
        commonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public Builder mergeCommon(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common value) {
      if (commonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          common_ != null &&
          common_ != cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.getDefaultInstance()) {
          getCommonBuilder().mergeFrom(value);
        } else {
          common_ = value;
        }
      } else {
        commonBuilder_.mergeFrom(value);
      }
      if (common_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public Builder clearCommon() {
      bitField0_ = (bitField0_ & ~0x00000001);
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.Builder getCommonBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCommonFieldBuilder().getBuilder();
    }
    /**
     * <code>.Common common = 1;</code>
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOrBuilder getCommonOrBuilder() {
      if (commonBuilder_ != null) {
        return commonBuilder_.getMessageOrBuilder();
      } else {
        return common_ == null ?
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.getDefaultInstance() : common_;
      }
    }
    /**
     * <code>.Common common = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOrBuilder> 
        getCommonFieldBuilder() {
      if (commonBuilder_ == null) {
        commonBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.Common.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOrBuilder>(
                getCommon(),
                getParentForChildren(),
                isClean());
        common_ = null;
      }
      return commonBuilder_;
    }

    private cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User user_;
    private com.google.protobuf.SingleFieldBuilder<
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOrBuilder> userBuilder_;
    /**
     * <code>.User user = 2;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.User user = 2;</code>
     * @return The user.
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.User user = 2;</code>
     */
    public Builder setUser(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
      } else {
        userBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.User user = 2;</code>
     */
    public Builder setUser(
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.User user = 2;</code>
     */
    public Builder mergeUser(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User value) {
      if (userBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          user_ != null &&
          user_ != cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.getDefaultInstance()) {
          getUserBuilder().mergeFrom(value);
        } else {
          user_ = value;
        }
      } else {
        userBuilder_.mergeFrom(value);
      }
      if (user_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.User user = 2;</code>
     */
    public Builder clearUser() {
      bitField0_ = (bitField0_ & ~0x00000002);
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.User user = 2;</code>
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.Builder getUserBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.User user = 2;</code>
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.User user = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.User.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private long emojiId_ ;
    /**
     * <code>int64 emojiId = 3;</code>
     * @return The emojiId.
     */
    @java.lang.Override
    public long getEmojiId() {
      return emojiId_;
    }
    /**
     * <code>int64 emojiId = 3;</code>
     * @param value The emojiId to set.
     * @return This builder for chaining.
     */
    public Builder setEmojiId(long value) {

      emojiId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 emojiId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmojiId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      emojiId_ = 0L;
      onChanged();
      return this;
    }

    private cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text emojiContent_;
    private com.google.protobuf.SingleFieldBuilder<
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.TextOrBuilder> emojiContentBuilder_;
    /**
     * <code>.Text emojiContent = 4;</code>
     * @return Whether the emojiContent field is set.
     */
    public boolean hasEmojiContent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.Text emojiContent = 4;</code>
     * @return The emojiContent.
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text getEmojiContent() {
      if (emojiContentBuilder_ == null) {
        return emojiContent_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.getDefaultInstance() : emojiContent_;
      } else {
        return emojiContentBuilder_.getMessage();
      }
    }
    /**
     * <code>.Text emojiContent = 4;</code>
     */
    public Builder setEmojiContent(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text value) {
      if (emojiContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        emojiContent_ = value;
      } else {
        emojiContentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Text emojiContent = 4;</code>
     */
    public Builder setEmojiContent(
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.Builder builderForValue) {
      if (emojiContentBuilder_ == null) {
        emojiContent_ = builderForValue.build();
      } else {
        emojiContentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Text emojiContent = 4;</code>
     */
    public Builder mergeEmojiContent(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text value) {
      if (emojiContentBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          emojiContent_ != null &&
          emojiContent_ != cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.getDefaultInstance()) {
          getEmojiContentBuilder().mergeFrom(value);
        } else {
          emojiContent_ = value;
        }
      } else {
        emojiContentBuilder_.mergeFrom(value);
      }
      if (emojiContent_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Text emojiContent = 4;</code>
     */
    public Builder clearEmojiContent() {
      bitField0_ = (bitField0_ & ~0x00000008);
      emojiContent_ = null;
      if (emojiContentBuilder_ != null) {
        emojiContentBuilder_.dispose();
        emojiContentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Text emojiContent = 4;</code>
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.Builder getEmojiContentBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getEmojiContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.Text emojiContent = 4;</code>
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.TextOrBuilder getEmojiContentOrBuilder() {
      if (emojiContentBuilder_ != null) {
        return emojiContentBuilder_.getMessageOrBuilder();
      } else {
        return emojiContent_ == null ?
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.getDefaultInstance() : emojiContent_;
      }
    }
    /**
     * <code>.Text emojiContent = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.TextOrBuilder> 
        getEmojiContentFieldBuilder() {
      if (emojiContentBuilder_ == null) {
        emojiContentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Text.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.TextOrBuilder>(
                getEmojiContent(),
                getParentForChildren(),
                isClean());
        emojiContent_ = null;
      }
      return emojiContentBuilder_;
    }

    private java.lang.Object defaultContent_ = "";
    /**
     * <code>string defaultContent = 5;</code>
     * @return The defaultContent.
     */
    public java.lang.String getDefaultContent() {
      java.lang.Object ref = defaultContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string defaultContent = 5;</code>
     * @return The bytes for defaultContent.
     */
    public com.google.protobuf.ByteString
        getDefaultContentBytes() {
      java.lang.Object ref = defaultContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string defaultContent = 5;</code>
     * @param value The defaultContent to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      defaultContent_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string defaultContent = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultContent() {
      defaultContent_ = getDefaultInstance().getDefaultContent();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string defaultContent = 5;</code>
     * @param value The bytes for defaultContent to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      defaultContent_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image backgroundImage_;
    private com.google.protobuf.SingleFieldBuilder<
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.ImageOrBuilder> backgroundImageBuilder_;
    /**
     * <code>.Image backgroundImage = 6;</code>
     * @return Whether the backgroundImage field is set.
     */
    public boolean hasBackgroundImage() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.Image backgroundImage = 6;</code>
     * @return The backgroundImage.
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image getBackgroundImage() {
      if (backgroundImageBuilder_ == null) {
        return backgroundImage_ == null ? cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.getDefaultInstance() : backgroundImage_;
      } else {
        return backgroundImageBuilder_.getMessage();
      }
    }
    /**
     * <code>.Image backgroundImage = 6;</code>
     */
    public Builder setBackgroundImage(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image value) {
      if (backgroundImageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        backgroundImage_ = value;
      } else {
        backgroundImageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.Image backgroundImage = 6;</code>
     */
    public Builder setBackgroundImage(
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.Builder builderForValue) {
      if (backgroundImageBuilder_ == null) {
        backgroundImage_ = builderForValue.build();
      } else {
        backgroundImageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.Image backgroundImage = 6;</code>
     */
    public Builder mergeBackgroundImage(cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image value) {
      if (backgroundImageBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          backgroundImage_ != null &&
          backgroundImage_ != cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.getDefaultInstance()) {
          getBackgroundImageBuilder().mergeFrom(value);
        } else {
          backgroundImage_ = value;
        }
      } else {
        backgroundImageBuilder_.mergeFrom(value);
      }
      if (backgroundImage_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Image backgroundImage = 6;</code>
     */
    public Builder clearBackgroundImage() {
      bitField0_ = (bitField0_ & ~0x00000020);
      backgroundImage_ = null;
      if (backgroundImageBuilder_ != null) {
        backgroundImageBuilder_.dispose();
        backgroundImageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Image backgroundImage = 6;</code>
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.Builder getBackgroundImageBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getBackgroundImageFieldBuilder().getBuilder();
    }
    /**
     * <code>.Image backgroundImage = 6;</code>
     */
    public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.ImageOrBuilder getBackgroundImageOrBuilder() {
      if (backgroundImageBuilder_ != null) {
        return backgroundImageBuilder_.getMessageOrBuilder();
      } else {
        return backgroundImage_ == null ?
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.getDefaultInstance() : backgroundImage_;
      }
    }
    /**
     * <code>.Image backgroundImage = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.ImageOrBuilder> 
        getBackgroundImageFieldBuilder() {
      if (backgroundImageBuilder_ == null) {
        backgroundImageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.Image.Builder, cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.ImageOrBuilder>(
                getBackgroundImage(),
                getParentForChildren(),
                isClean());
        backgroundImage_ = null;
      }
      return backgroundImageBuilder_;
    }

    private boolean fromIntercom_ ;
    /**
     * <code>bool fromIntercom = 7;</code>
     * @return The fromIntercom.
     */
    @java.lang.Override
    public boolean getFromIntercom() {
      return fromIntercom_;
    }
    /**
     * <code>bool fromIntercom = 7;</code>
     * @param value The fromIntercom to set.
     * @return This builder for chaining.
     */
    public Builder setFromIntercom(boolean value) {

      fromIntercom_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool fromIntercom = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromIntercom() {
      bitField0_ = (bitField0_ & ~0x00000040);
      fromIntercom_ = false;
      onChanged();
      return this;
    }

    private boolean intercomHideUserCard_ ;
    /**
     * <code>bool intercomHideUserCard = 8;</code>
     * @return The intercomHideUserCard.
     */
    @java.lang.Override
    public boolean getIntercomHideUserCard() {
      return intercomHideUserCard_;
    }
    /**
     * <code>bool intercomHideUserCard = 8;</code>
     * @param value The intercomHideUserCard to set.
     * @return This builder for chaining.
     */
    public Builder setIntercomHideUserCard(boolean value) {

      intercomHideUserCard_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool intercomHideUserCard = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntercomHideUserCard() {
      bitField0_ = (bitField0_ & ~0x00000080);
      intercomHideUserCard_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:EmojiChatMessage)
  }

  // @@protoc_insertion_point(class_scope:EmojiChatMessage)
  private static final cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage();
  }

  public static cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmojiChatMessage>
      PARSER = new com.google.protobuf.AbstractParser<EmojiChatMessage>() {
    @java.lang.Override
    public EmojiChatMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmojiChatMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmojiChatMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.EmojiChatMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

