// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: douyin_hack/webcast/im/LikeMessage.proto
// Protobuf Java Version: 4.32.1

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

@com.google.protobuf.Generated
public final class LikeMessageOuterClass extends com.google.protobuf.GeneratedFile {
  private LikeMessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      LikeMessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcast_im_LikeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webcast_im_LikeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(douyin_hack/webcast/im/LikeMessage.pro" +
      "to\022\nwebcast.im\032#douyin_hack/webcast/im/C" +
      "ommon.proto\032#douyin_hack/webcast/data/Us" +
      "er.proto\"\251\002\n\013LikeMessage\022\"\n\006common\030\001 \001(\013" +
      "2\022.webcast.im.Common\022\r\n\005count\030\002 \001(\003\022\r\n\005t" +
      "otal\030\003 \001(\003\022\r\n\005color\030\004 \001(\003\022 \n\004user\030\005 \001(\0132" +
      "\022.webcast.data.User\022\014\n\004icon\030\006 \001(\t\022\032\n\022dou" +
      "ble_like_detail\030\007 \001(\014\022\034\n\024display_control" +
      "_info\030\010 \001(\014\022\031\n\021linkmic_guest_uid\030\t \001(\003\022\r" +
      "\n\005scene\030\n \001(\t\022\031\n\021pico_display_info\030\013 \001(\014" +
      "\022\032\n\022public_area_common\030\014 \001(\014BG\nCcool.scx" +
      ".live_room_watcher.impl.douyin_hack.prot" +
      "o_entity.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOuterClass.getDescriptor(),
          cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOuterClass.getDescriptor(),
        });
    internal_static_webcast_im_LikeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webcast_im_LikeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webcast_im_LikeMessage_descriptor,
        new java.lang.String[] { "Common", "Count", "Total", "Color", "User", "Icon", "DoubleLikeDetail", "DisplayControlInfo", "LinkmicGuestUid", "Scene", "PicoDisplayInfo", "PublicAreaCommon", });
    descriptor.resolveAllFeaturesImmutable();
    cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im.CommonOuterClass.getDescriptor();
    cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.data.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
