// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin_hack/webcast/im/LinkerDegradeAlertContent.proto

// Protobuf Java Version: 3.25.2
package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public interface LinkerDegradeAlertContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkerDegradeAlertContent)
    com.google.protobuf.MessageOrBuilder {
}
