// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LinkerKickOutContent.proto

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public final class LinkerKickOutContentOuterClass {
  private LinkerKickOutContentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LinkerKickOutContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LinkerKickOutContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%webcast/im/LinkerKickOutContent.proto\"" +
      "\026\n\024LinkerKickOutContentBG\nCcool.scx.live" +
      "_room_watcher.impl.douyin_hack.proto_ent" +
      "ity.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LinkerKickOutContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LinkerKickOutContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LinkerKickOutContent_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
