// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin_hack/webcast/im/LinkerCloseContent.proto

// Protobuf Java Version: 3.25.3
package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public interface LinkerCloseContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkerCloseContent)
    com.google.protobuf.MessageOrBuilder {
}
