// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin_hack/webcast/im/LinkerCancelContent.proto

// Protobuf Java Version: 4.26.0
package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public interface LinkerCancelContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkerCancelContent)
    com.google.protobuf.MessageOrBuilder {
}
