// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: douyin_hack/webcast/im/LinkerKickOutContent.proto
// Protobuf Java Version: 4.27.1

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public interface LinkerKickOutContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkerKickOutContent)
    com.google.protobuf.MessageOrBuilder {
}
