// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin_hack/webcast/im/LinkerBattleConnectContent.proto

// Protobuf Java Version: 4.26.1
package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public interface LinkerBattleConnectContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkerBattleConnectContent)
    com.google.protobuf.MessageOrBuilder {
}
