// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin_hack/webcast/im/LinkerChangeMultiPKTeamInfoContent.proto

// Protobuf Java Version: 3.25.1
package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public interface LinkerChangeMultiPKTeamInfoContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkerChangeMultiPKTeamInfoContent)
    com.google.protobuf.MessageOrBuilder {
}
