// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: douyin_hack/webcast/im/RoomMsgTypeEnum.proto
// Protobuf Java Version: 4.27.2

package cool.scx.live_room_watcher.impl.douyin_hack.proto_entity.webcast.im;

public final class RoomMsgTypeEnumOuterClass {
  private RoomMsgTypeEnumOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      RoomMsgTypeEnumOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,douyin_hack/webcast/im/RoomMsgTypeEnum" +
      ".proto*\335\001\n\017RoomMsgTypeEnum\022\022\n\016DEFAULTROO" +
      "MMSG\020\000\022\035\n\031ECOMLIVEREPLAYSAVEROOMMSG\020\001\022\033\n" +
      "\027CONSUMERRELATIONROOMMSG\020\002\022\034\n\030JUMANJIDAT" +
      "AAUTHNOTIFYMSG\020\003\022\020\n\014VSWELCOMEMSG\020\004\022\022\n\016MI" +
      "NORREFUNDMSG\020\005\022\037\n\033PAIDLIVEROOMNOTIFYANCH" +
      "ORMSG\020\006\022\025\n\021HOSTTEAMSYSTEMMSG\020\007BG\nCcool.s" +
      "cx.live_room_watcher.impl.douyin_hack.pr" +
      "oto_entity.webcast.imP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
