// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LandscapeAreaCommon.proto

package cool.scx.live_room_watcher.douyin_hack.proto_entity.webcast.im;

public interface LandscapeAreaCommonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LandscapeAreaCommon)
    com.google.protobuf.MessageOrBuilder {
}
