// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast/im/LinkPrepareApplyContent.proto

package cool.scx.live_room_watcher.douyin_hack.proto_entity.webcast.im;

public interface LinkPrepareApplyContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkPrepareApplyContent)
    com.google.protobuf.MessageOrBuilder {
}
